[build]
command = "npm run build:client"
functions = "netlify/functions"
publish = "dist/spa"

[functions]
external_node_modules = []
node_bundler = "esbuild"
included_files = ["node_modules/@supabase/**", "node_modules/express/**", "node_modules/cors/**", "node_modules/serverless-http/**"]

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"